apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  type: {{ .Values.app.service.type }}
  selector:
    app: {{ .Values.app.labels.app }}
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}