events {}

http {
    upstream flask_backend {
        server flask1:80;
        server flask2:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://flask_backend;
        }
    }
}