---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.redis.name }}
spec:
  serviceName: {{ .Values.redis.name }}
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.redis.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.name }}
    spec:
      containers:
      - name: {{ .Values.redis.name }}
        image: {{ .Values.redis.image.name }}:{{ .Values.redis.image.tag }}
        ports:
        - containerPort: {{ .Values.redis.port }}
          name: client
        volumeMounts:
        - name: data
          mountPath: /data
          readOnly: false
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: {{ .Values.redis.storageSize }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.redis.name }}
  ports:
    - name: client
      port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
      protocol: TCP
